@JwtAuthDotNet_HostAddress = http://localhost:5131

GET {{JwtAuthDotNet_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{JwtAuthDotNet_HostAddress}}/api/user/add-user
Content-Type: application/json 
{
    "UserName": "teste1234",
    "Password": "teste123",
    "Role": "Manager"
}

